typedef enum {
    TOKEN_BEGIN,
    TOKEN_END,
    TOKEN_MOUSE_CLICK,
    TOKEN_KEYBOARD_UP,
    TOKEN_TIMEOUT,
    TOKEN_NUMBER,
    TOKEN_IDENTIFIER,
    TOKEN_LPAREN,
    TOKEN_RPAREN,
    TOKEN_SEMICOLON,
    TOKEN_EOF
} TokenType;